using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace marvel-test-one-dotnet.Controllers
{
    [Route("")]
    [ApiController]
    public class DefaultController : ControllerBase
    {
        // GET
        [HttpGet]
        public ActionResult<IEnumerable<string>> Get()
        {
            return new string[] { "Welcome to marvel-test-one-dotnet application ! This application is generated by KloverCloud" };
        }

        // POST
        [HttpPost]
        public void Post([FromBody] string value)
        {
        }

        // PUT /id
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE /id
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}
